displayName=Adventurer's Log
author=IronFleur
description=A plugin to track the date and time you achieved certain milestones, such as quest completion, level up, boss kills and collection log entries.
tags=log, kc, boss, quest, levels
plugins=com.runitebar.adventurerslog.AdventurersLogPlugin